[package]
name = "custom_vector_objones25"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
proptest = "1.3.1"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "performance"
harness = false
